[tool.poetry]
name = "pynotate"
version = "0.1.0"
description = ""
authors = ["ClementPla <clement.playout@polymtl.ca>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
pyzmq = "^26.2.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
